// This file was autogenerated by client/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../tetriweb/graphics.js', ['tetriweb.Graphics'], ['goog.array', 'goog.dom']);
goog.addDependency('../../tetriweb/keyevents.js', ['tetriweb.KeyEvents'], ['goog.events', 'goog.events.KeyHandler', 'tetriweb.Graphics', 'tetriweb.Tetris']);
goog.addDependency('../../tetriweb/tetrinet.js', ['tetriweb.Tetrinet'], ['goog.events', 'goog.net.XhrIo', 'tetriweb.Graphics']);
goog.addDependency('../../tetriweb/tetris.js', ['tetriweb.Tetris'], ['goog.array', 'tetriweb.Graphics']);
goog.addDependency('../../tetriweb/tetriweb.js', ['tetriweb'], ['goog.dom', 'goog.events', 'goog.ui.Dialog', 'tetriweb.KeyEvents', 'tetriweb.Tetrinet', 'tetriweb.Tetris']);
